behaviors:
  Martial:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 2048
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: True
      hidden_units: 32
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: True
          hidden_units: 32
          num_layers: 2
      gail:
        strength: 0.1
        demo_path: MasterArts/MartialMaster.demo
        network_settings:
          normalize: True
          hidden_units: 32
          num_layers: 2
    behavioral_cloning:
      strength: 0.5
      demo_path: MasterArts/MartialMaster.demo
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000